// ── Brand-strip tests over REAL catalogue names ──────────────────────────────
// Every input below is a live product name lifted verbatim from a read-only
// /products census on 2026-08-13 (typos, trailing spaces and curly apostrophes
// included). Expected outputs were generated by the function and then reviewed
// by eye before being frozen here — a change in behaviour must be deliberate.
import { describe, it, expect } from "vitest";
import { stripBrandFromName, shopifyTitle, brandsIn, BRAND_PATTERNS } from "./nameRewrite.mjs";

// [input, expected]
const CASES = [
  // Nike
  ["Nike Shox TL Blue Black", "Shox TL Blue Black"],
  ["Nike Air Force 1 What The LA Multi-Color", "Air Force 1 What The LA Multi-Color"],
  ["Nike Air Max 95 Greedy Orange", "Air Max 95 Greedy Orange"],
  ["Nike Zoom Vomero Roam Brown", "Zoom Vomero Roam Brown"],
  ["Nike dri- fit cap khaki", "Dri- fit cap khaki"],
  // Nike + NOCTA in one name — NOCTA is a kept LINE mark, Nike still goes
  [
    "Nike Air Force 1 Low Drake NOCTA Certified Lover Boy Palest Purple",
    "Air Force 1 Low Drake NOCTA Certified Lover Boy Palest Purple",
  ],
  // adidas (both casings live in the catalogue)
  ["Adidas Gazelle Indoor blue and grey", "Gazelle Indoor blue and grey"],
  ["Adidas Samba Wonder White Maroon", "Samba Wonder White Maroon"],
  [
    "adidas Copa Pure 2 Elite Firm Ground Boots featuring a black leather upper with white stripes.",
    "Copa Pure 2 Elite Firm Ground Boots featuring a black leather upper with white stripes.",
  ],
  // Jordan — kept LINE mark (owner decision): the mark IS the model identity
  ["Air Jordan 1 Retro Low OG Zion Williamson Grey Blue", "Air Jordan 1 Retro Low OG Zion Williamson Grey Blue"],
  ["Air Jordan 13 Black White", "Air Jordan 13 Black White"],
  ["Jordan backpack white", "Jordan backpack white"],
  // Puma — club names (Borussia Dortmund) stay, they are the product
  ["Puma Speedcat Pink", "Speedcat Pink"],
  ["Puma Borussia Dortmund Jersey Yellow Black", "Borussia Dortmund Jersey Yellow Black"],
  // New Balance
  ["New Balance 9060 Navy Beige", "9060 Navy Beige"],
  ["New balance 9060 creem ", "9060 creem"],
  // Lacoste + live misspelling
  ["Lacoste golf t shirt navy: LCE-3431", "Golf t shirt navy: LCE-3431"],
  ["Lacoster spinor sneaker navy with black", "Spinor sneaker navy with black"],
  // Boss family
  ["Hugo Boss beanie navy #1", "Beanie navy #1"],
  ["Boss t shirt green ", "T shirt green"],
  ["Hugo boss adjustable cap white #1", "Adjustable cap white #1"],
  // Louis Vuitton — incl. the all-brand name that must empty out
  ["Louis Vuitton time out white", "Time out white"],
  ["Karl Lagerfeld Slides Beige", "Slides Beige"],
  // Fear of God / Essentials — both marks in one name
  ["Fear of God Essentials T-Shirt Light Grey", "T-Shirt Light Grey"],
  ["Essentials bag brown #9138", "Bag brown #9138"],
  ["Diesel t shirt cream white: 216#", "T shirt cream white: 216#"],
  ["Alo Yoga Airlift Solar Visor Navy/ shine ", "Airlift Solar Visor Navy/ shine"],
  // On Running — leading-word rule only
  ["On Cloudsurfer Light Grey", "Cloudsurfer Light Grey"],
  ["On Cloudventure 2 White", "Cloudventure 2 White"],
  // Gucci + live misspelling
  ["Gucci Princetown Black", "Princetown Black"],
  ["Guccie slidebag ", "Slidebag"],
  // Armani family
  ["Armani exchange beanie green ", "Beanie green"],
  ["Emporio underwear #15", "Underwear #15"],
  // Calvin Klein — a branded perfume DOES lose its brand; + live misspelling
  ["Calvin Klein one essence perfume", "One essence perfume"],
  ["Kelvin Klein bag black #z16006", "Bag black #z16006"],
  // Ralph Lauren — "Polo Ralph" is brand, bare "Polo" (the garment) is not
  ["Polo Ralph beanie green", "Beanie green"],
  // accessories
  ["Daniel wellington watch gold end black", "Watch gold end black"],
  ["Rolex Watch", "Watch"],
  ["Levi’s beanie navy #5", "Beanie navy #5"],
  ["Timberland beanie brown ", "Beanie brown"],
  ["Balenciaga Speed 2.0 Black White", "Speed 2.0 Black White"],
  [" Hoka Rocket X 2 green yellow ", "Rocket X 2 green yellow"],
  ["Under Armour full black", "Full black"],
  ["The North Face Glenclyffe Low Green", "Glenclyffe Low Green"],
  ["Converse Chuck Taylor All Star Low White", "Chuck Taylor All Star Low White"],
  ["Dsquared2 Never Stretch Collar T-Shirt Black", "Never Stretch Collar T-Shirt Black"],
  ["True Religion T-Shirt White", "T-Shirt White"],
  ["Tommy Hilfiger Tracksuit Navy", "Tracksuit Navy"],
  ["Birkenstock Boston Black", "Boston Black"],
  ["Dolce & Gabbana White Blue Denim", "White Blue Denim"],
];

// One-size perfume house names carry no brand mark — they must pass through
// byte-identical (they are already the whole identity of the product).
const PASS_THROUGH = [
  "Verato Amber",
  "Honeyed Fantasy",
  "Champ De Rose",
  "Roses D'emotion",
  "Catwalk",
  "Just Choco",
  "Nebras",
];

describe("stripBrandFromName — real catalogue names", () => {
  it.each(CASES)("%j → %j", (input, expected) => {
    expect(stripBrandFromName(input)).toBe(expected);
  });

  it.each(PASS_THROUGH)("perfume/unbranded name passes through: %j", (name) => {
    expect(stripBrandFromName(name)).toBe(name);
  });

  it("a name that is nothing but brand empties out (caller must flag it)", () => {
    expect(stripBrandFromName("Louis Vuitton ")).toBe("");
    expect(stripBrandFromName("Rolex")).toBe("");
  });

  it("no brand word survives in any output", () => {
    for (const [input] of CASES) {
      const out = stripBrandFromName(input);
      expect(brandsIn(out), `brand left in ${JSON.stringify(out)} (from ${JSON.stringify(input)})`).toEqual([]);
    }
  });

  it("is idempotent", () => {
    for (const [input] of CASES) {
      const once = stripBrandFromName(input);
      expect(stripBrandFromName(once)).toBe(once);
    }
  });

  it("does not shred ordinary words containing brand substrings", () => {
    // "on" inside a name, "alo" inside Buffalo, "ck"/"lv" inside words
    expect(stripBrandFromName("Slip on sandals black")).toBe("Slip on sandals black");
    expect(stripBrandFromName("Buffalo plaid shirt")).toBe("Buffalo plaid shirt");
    expect(stripBrandFromName("Black silver buckle belt")).toBe("Black silver buckle belt");
    // bare "Polo" is a garment, not a brand word
    expect(stripBrandFromName("Polo neck jersey navy")).toBe("Polo neck jersey navy");
  });

  it("line marks survive even when the parent brand is present (synthetic pairing)", () => {
    expect(stripBrandFromName("Nike Air Jordan 1 Low")).toBe("Air Jordan 1 Low");
    expect(stripBrandFromName("Nike NOCTA hoodie black")).toBe("NOCTA hoodie black");
  });

  it("handles null/empty defensively", () => {
    expect(stripBrandFromName("")).toBe("");
    expect(stripBrandFromName(null)).toBe("");
    expect(stripBrandFromName(undefined)).toBe("");
  });

  it("every pattern is global + case-insensitive (removal must catch repeats)", () => {
    for (const re of BRAND_PATTERNS) {
      expect(re.flags).toContain("g");
      expect(re.flags).toContain("i");
    }
  });

  it("brandsIn returns clean canonical names (no regex anchors leaking through)", () => {
    expect(brandsIn("Nike Air Force 1")).toEqual(["nike"]);
    expect(brandsIn("New Balance 9060")).toEqual(["new balance"]);
    expect(brandsIn("Hugo Boss beanie")).toEqual(["hugo boss"]);
  });

  it("no pattern strips a kept line mark (list-level pin of the allowlist)", () => {
    for (const mark of ["Air Jordan", "Jordan", "NOCTA"]) {
      expect(stripBrandFromName(`${mark} test case`)).toBe(`${mark} test case`);
    }
  });
});

// ── shopifyTitle — the guarded entry point payload builders use ──────────────
describe("shopifyTitle — guards", () => {
  it("all-brand name empties out → flagged, original ships (live 'Louis Vuitton ')", () => {
    expect(shopifyTitle("Louis Vuitton ")).toEqual({
      title: "Louis Vuitton",
      flagged: true,
      reason: "empty after strip",
    });
  });

  it("digit-leading rewrite → flagged, original ships (live 'New balance 9060 creem ')", () => {
    expect(shopifyTitle("New balance 9060 creem ")).toEqual({
      title: "New balance 9060 creem",
      flagged: true,
      reason: "digit-leading after strip",
    });
  });

  it("rewrite shorter than 3 chars → flagged, original ships (synthetic)", () => {
    expect(shopifyTitle("Nike A")).toEqual({
      title: "Nike A",
      flagged: true,
      reason: "shorter than 3 chars after strip",
    });
  });

  it("Air Jordan line mark passes clean and unflagged", () => {
    expect(shopifyTitle("Air Jordan 1 Retro Low OG Zion Williamson Grey Blue")).toEqual({
      title: "Air Jordan 1 Retro Low OG Zion Williamson Grey Blue",
      flagged: false,
      reason: null,
    });
  });

  it("NOCTA line mark survives while Nike is stripped, unflagged", () => {
    expect(shopifyTitle("Nike Air Force 1 Low Drake NOCTA Certified Lover Boy Palest Purple")).toEqual({
      title: "Air Force 1 Low Drake NOCTA Certified Lover Boy Palest Purple",
      flagged: false,
      reason: null,
    });
  });

  it("an ordinary strip passes through unflagged", () => {
    expect(shopifyTitle("Nike Zoom Vomero Roam Brown")).toEqual({
      title: "Zoom Vomero Roam Brown",
      flagged: false,
      reason: null,
    });
  });
});
