// Vitest — pure HTML builder (no DOM needed for the string assertions).
import { describe, it, expect } from "vitest";
import { buildPickListHtml } from "./pickList";

const spec = {
  title: "Move Excess Pick List",
  route: "Marathon PE → Hub 2",
  generatedBy: "warehouse",
  now: new Date("2026-07-14T08:00:00Z"),
  groups: [
    { name: "Zeta Tee Black", photoUrl: "https://x/p.jpg", lines: [{ label: "M", qty: 3 }, { label: "L", qty: 2 }] },
    { name: "Alpha Hoodie Grey", lines: [{ label: "XL", qty: 1 }] },
  ],
};

describe("buildPickListHtml", () => {
  it("carries header, route, totals and operator", () => {
    const html = buildPickListHtml(spec);
    expect(html).toContain("Move Excess Pick List");
    expect(html).toContain("Marathon PE → Hub 2");
    expect(html).toContain("Total products: <b>2</b>");
    expect(html).toContain("Total units: <b>6</b>");
    expect(html).toContain("Generated by: <b>warehouse</b>");
  });

  it("groups sizes per product and sorts alphabetically (brand-first names)", () => {
    const html = buildPickListHtml(spec);
    expect(html.indexOf("Alpha Hoodie Grey")).toBeLessThan(html.indexOf("Zeta Tee Black"));
    expect(html).toContain("M ×3");
    expect(html).toContain("L ×2");
    // one row per product, not per size
    expect(html.match(/class="item"/g)).toHaveLength(2);
  });

  it("renders checklist, signature footer, and the no-stock-moved disclaimer", () => {
    const html = buildPickListHtml(spec);
    for (const s of ["☐ Picked", "☐ Verified", "☐ Loaded", "Completed by", "Signature", "Notes", "no stock has moved"]) {
      expect(html).toContain(s);
    }
  });

  it("escapes product names and falls back when a photo is missing", () => {
    const html = buildPickListHtml({ ...spec, groups: [{ name: "<b>Rogue & Co</b>", lines: [{ label: "M", qty: 1 }] }] });
    expect(html).toContain("&lt;b&gt;Rogue &amp; Co&lt;/b&gt;");
    expect(html).toContain("no photo");
  });
});
